### ISSUE TITLE
Tubeup uploads all items with "_" as title

### ISSUE THREAD

**Issue by ghost** [bibanon/tubeup#103]
All items uploaded are currently titled "_"

As seen here:
https://i.imgur.com/STmMNyn.png

youtube-dl = 2019.08.02 (updated after the fact)
tubeup = 0.0.17
ia = 1.8.1

**Comment by DuckHP** [comment]
re-tubeuping the items, does not repair the missing title

**Comment by vxbinaca** [comment]
Upgrade your youtube-dl before each use every single time without failure.

**Comment by vxbinaca** [comment]
Update internetarchive too.

**Comment by vxbinaca** [comment]
You can't fix it you'll have to delete the contents of each item, re-rip then rename by hand each item. Good luck.

**Comment by DuckHP** [comment]
I beered this up so far

`#!/bin/sh

#A script intended solely to repair a given list of IA tubeup'ed items suffering from "_" caused by breakage via youtube-dl
# By DuckHP
# License: PD/ Public Domain / 0 License / Unlicense

YOUTUBEDL_VERSION=$(youtube-dl --version)
YOUTUBEDL_FOUND=$?
if [ $YOUTUBEDL_FOUND -eq 0 ] && [ $YOUTUBEDL_VERSION == '2019.08.02' ]
then
	echo "✔ 'youtube-dl' version found: $YOUTUBEDL_VERSION"
	YOUTUBEDL_FOUND='YES'
else
	echo "'youtube-dl' command missing or unintended version"
fi

IA_VERSION=$(ia --version)
IA_FOUND=$?
if [ $IA_FOUND -eq 0 ] && [ $IA_VERSION == '1.8.1' ]
then
	echo "✔ 'ia' version found: $IA_VERSION"
	IA_FOUND='YES'
else
	echo "'ia' command missing or unintended version"
fi

TUBEUP_VERSION=$(tubeup --version)
TUBEUP_FOUND=$?
if [ $TUBEUP_FOUND -eq 0 ] && [ $TUBEUP_VERSION == '0.0.17' ]
then
	echo "✔ 'tubeup' version found: $TUBEUP_VERSION"
	TUBEUP_FOUND='YES'
else
	echo "'tubeup' command missing or unintended version"
fi


if [ $TUBEUP_FOUND=='YES' ] && [ $IA_FOUND=='YES' ] && [ $YOUTUBEDL_FOUND=='YES' ]
then
	echo 'Good to go!! Skål1!'
fi

#get a list of IA items to be potentially reworked
#pull item youtube id via 'ia metada 'item'
#if title is "_" as opposed to original title from youtube-dl ;
#	grab existing ia metadata and parse json
#	get title from metadata via new youtube-dl
#		parse json and compare
#			grab title of original , and correct using 'ia metadata <item> --modify=<title:GRABBED_TITLE>' command if incorrect
`

**Comment by brandongalbraith** [comment]
Can you create this as a Gist and drop the gist link in here?

**Comment by vxbinaca** [comment]
Thanks for the script I'll check this in a bit. Gathering items tht got hit by this, luckily they're literally all on one collection and I stopped any rips for youtube, upgraded everything and am pausing until I get this at least journaled so I can work on it at some later point.

**Comment by brandongalbraith** [comment]
@DuckHP @vxbinaca Can either of you reproduce this? I'm unable to on a test suite of youtube videos running with the latest versions of tubeup, youtube-dl, and ia.

**Comment by vxbinaca** [comment]
Reproduce the error or the script? The error was related to a bug in youtube-dl (site layout change) that didn't put the title in Metadata.

**Comment by brandongalbraith** [comment]
> Reproduce the error or the script? The error was related to a bug in youtube-dl (site layout change) that didn't put the title in Metadata.

Thanks for that, I didn't see that context in this thread.

> All of my items that got hit by this were in one collection and I journaled which were affected. I'll get around to testing this script later.

:+1:

**Comment by vxbinaca** [comment]
I should add that upgrading youtube-dl will fix this for future rips. Problem here is - and I wasn't immune to this (130 items) - some people get complacent about upgrading dependencies.

**Comment by brandongalbraith** [comment]
Instead of using a script to rename objects in the Internet Archive, it's probably easier and more straightforward to re-upload videos (if they're still available) and then delete the improperly named items in IA.

**Comment by vxbinaca** [comment]
I can live with mangled file names those can be easily fixed by another generation, but that metadata very important. So I'm of the opposite view that the videos don't need a re-rip. Just a Metadata correction which can be done in-place with only minimal interaction with youtube. Hell you could fix the filenames too with the correct Metadata.

**Comment by DuckHP** [comment]
@vxbinaca @brandongalbraith  I'm currently trying to snag the ._info.json_ and ._description_ files of affected items to [tubefix_metadata00](https://archive.org/download/tubefix_metadata00) . But then at least some of the missing metadata could perhaps be grabbed from there at a later point.

I currently got a list of 5341 items that are seemingly affected (by looking for _ titled items)

I've githubbed a now non-working version of the thingy that i used to identify those items to https://github.com/DuckHP/iatubefixr . But, it will need to be doing searching via more than one sessions/threads, otherwise it's painfully slow to say the least.

I wish i had more experience working with the 'internetarchive' python module to implement more than mere _possibly_ identifying affected items, so that it could also retitle and rename files to the corresponding works. But at this point, i'm not even sure if it's quering IA optimally :/

**Comment by DuckHP** [comment]
> Instead of using a script to rename objects in the Internet Archive, it's probably easier and more straightforward to re-upload videos (if they're still available) and then delete the improperly named items in IA.

The easiest, and least resource demaniding i guess would be to rename the already existing files in items. (and derivatives are maybe renamed accordingly as well then, i'm not sure.)

**Comment by brandongalbraith** [comment]
Your time is worth more than some compute and bandwidth resources.

**Comment by brandongalbraith** [comment]
🤷🏻‍♂️Go for it then.

**Comment by DuckHP** [comment]
@brandongalbraith 
https://github.com/DuckHP/iatubefixr should hopefully be slightly more useful now, in regards to finding possibly affected items.
e.g:
`python src/tubefix.py --uploader <ia uploader email> --maxsessions 4`

as it is it's still gonna need grep'ing etc. , of the output

**Comment by vxbinaca** [comment]
I have only 132 videos effected by this. Piping or individual item support would be nice so I could just bang out a batch file in nvim.

Also thanks again for this.

If you're confident your script works and won't mangle things up, try this for deleting:

`-H x-archive-keep-old-version:0`

So it doesn't put the old videos and Metadata in the history folder.

I want to warn you extreme caution when playing with that flag. It does changes irrevocably. It's like deleting pools on ZFS.

**Comment by DuckHP** [comment]
@vxbinaca It seems like there's only 5341 items possibly affected, i'm not quite sure. But i've apparently managed to download the .info.json , .description (and threw in subtitles in case), at least for ~4118 of those. Which i'm now currently putting into https://archive.org/details/tubefix_metadata00 item.

Here's the list of youtube urls i gathered btw https://archive.org/download/tubefix_metadata00/affected_urls.txt

Come to think of it in hindsight. I probably should've written them into _<id>-_named subfolders in the item, for easier retrieval ... :face_with_thermometer:

**Comment by vxbinaca** [comment]
You're better off than me. IAs deindex bs I had to do it by hand. Only took me 10 minutes to retrieve the URLs would have been easier if I could have just used the normal search function. I've slowed ingestion so the damage in my case was limited. Also limiting it further was only one extractor had the issue.

Lessons learned: Always update dependencies before using Tubeup. Check output while uploading. Check the downloads folder for missed uploads and process those video IDs out of the download archive.

**Comment by DuckHP** [comment]
btw, i just tried a computer i havent used in a while, and youtube-dl==2019.7.2 + tubeup==0.0.16 will definetaly cause _ named items

**Comment by vxbinaca** [comment]
Yup it was a bug in youtube-dl alone. A site change that messed up the extractor. I'm considering locking in `internetarchive` versions on every release to force a upgrade, along with the minimum of the current version of youtube-dl on push to pypi.
