### ISSUE TITLE
Censorship on this project

### ISSUE THREAD

**Issue by nihelmasell** [bibanon/tubeup#115]
Well, we often make claims about censorship on media and some type of forums (the reason for archiving) and now I see the same actions are performed here. I just asked how can I adapt my 20tb YouTube archive to be uploaded to the IA, in case it is deleted (as it often is on YouTube). First, the issue was closed, and know I cant even take part of it. I know your gonna delete this message, but want to show your contradictions. Goodbye.

**Comment by antonizoon** [comment]
Look man, people don't pay a cent to upload to the Internet Archive, and the Internet Archive yet they have to hold the bag on storing 20TB of data forever along with handling all the possible DMCA or other litigation that took it down from YouTube in the first place. 

> The problem is some channels have 30,000 videos, which overpopulate my folders,

The limitations you are encountering on mirroring 30,000/20TB videos are not set by us, it is set by the Internet Archive which has to pay to hold that much data. Have you ever thought about how much data that is and how much it costs to make that available to the public to access the way they host it with redundant storage? Our script is already under restrictions by the Internet Archive due to excessive and thoughtless upload, we cannot provide any further countermeasures because it is not our right to do so.

Quite frankly, a practically infinite data source is not going to fit on a finite server system and limited funding.

**Comment by nihelmasell** [comment]
1) I never said I wanted to backup ALL 20tb to the archive.
2) I wanted to skip re downloading the material I already have. That’s all. If I wanted to upload 20tb I still could. It would just take more time.
3) People upload lots of stuff to the archive. Eg: webcam feeds 24/365 for hundreds of cities, Blu-ray/ 4K webrips of movies (sometimes reaching 50tb each), Flickr and Instagram backups, complete websites, etc. I think it’s up to them to ban me if they want to.
