### ISSUE TITLE
Switch video downloader

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#129]
[Someone has mirrored the codebase](https://github.com/blackjack4494/youtube-dlc )of youtube-dl and just merged in PRs the YTDL staff refuse to look into.

YTDL releases used to be bi-weekly at the beginning of the year and are now bi-monthly, currently youtube ripping is partially working at best. Dstfw has[ admitted he no longer has the time](https://github.com/ytdl-org/youtube-dl/issues/26462#issuecomment-684031808) to maintain the project and the 5 other staff members aren't stepping up.

If theres library compatibility, I should be able to handle simply forcing a depend for youtube-dlc and just dropping youtube-dl. Currently it's not compiling due to a flake8 error according to travis-ci.

Edit: It's working as of this edit.

**Comment by refeed** [comment]
I've been offline for a while from GitHub. Well, that's sad :(

I haven't check the codebase, and haven't run youtube-dlc yet, but I think it can be as easy as just changing the library name, I think youtube-dlc won't change the API calls (I hope youtube-dlc's maintainers are good programmers) from the previous youtube-dl.

Don't worry about the `flake8`, I placed there just so that the code doesn't look so messy, the code can still run as long as the unittests still runs (I hope everybody create tests for each PRs here, otherwise, well no problem if our priority isn't code quality). It's still good to comply with flake8 rules though

**Comment by vxbinaca** [comment]
Youtube-dl was taken down with a DMCA complaint.

**Comment by refeed** [comment]
Yeah :(, and I'm not aware of any video downloader that can do the same. It's still available in pip though, I also heard they moved their codebase to GitLab https://gitlab.com/ytdl-org/youtube-dl , idk what will happen next

**Comment by vxbinaca** [comment]
> Yeah :(, and I'm not aware of any video downloader that can do the same. It's still available in pip though, I also heard they moved their codebase to GitLab https://gitlab.com/ytdl-org/youtube-dl , idk what will happen next

youtube-dlc, because the youtube-dl devs wern't maintaing their codebase.

Holy shit I just realized all those years of backlogged PRs on their repo are fucking gone. No way I trust the devs anymore to maintain it. All that work of people is gone because they can't be assed to merge code.

youtube-dlc for sure.

**Comment by spiralofhope** [comment]
FYI [youtube-dlc](https://github.com/blackjack4494/youtube-dlc) is gone as well.

**Comment by vxbinaca** [comment]
> FYI [youtube-dlc](https://github.com/blackjack4494/youtube-dlc) is gone as well.

not quite but ne heeds to find a new host.

**Comment by vxbinaca** [comment]
Video downloader switched.
