### ISSUE TITLE
Some queries regarding the code

### ISSUE THREAD

**Issue by pukkandan** [bibanon/tubeup#151]
Hi, I was looking into tubeup because of https://github.com/pukkandan/yt-dlp/issues/42 by @DarkMahesvara
Related: https://github.com/bibanon/tubeup/pull/146, https://github.com/bibanon/tubeup/issues/119

I was thinking of making a PR here to solve the issue (for youtube only - a general solution for all extractors is impossible). But, while going through the code, I noticed some odd things. Before I write any code for the project, it would help me to know if any of these are intentional. I have no knowledge of the archive.org's upload mechanism, so sorry if some of the questions are dumb

---

1. Why? This simply asks youtube-dl to print the JSON into the terminal, but I don't see where you use that info
https://github.com/bibanon/tubeup/blob/b18c8175f2a2ed4de8f114e2dd5f2325c532b241/tubeup/TubeUp.py#L233

2. Why write this info to file and then read back from it instead of getting it directly from infodict?
https://github.com/bibanon/tubeup/blob/b18c8175f2a2ed4de8f114e2dd5f2325c532b241/tubeup/TubeUp.py#L234-L235
https://github.com/bibanon/tubeup/blob/b18c8175f2a2ed4de8f114e2dd5f2325c532b241/tubeup/TubeUp.py#L284-L287
https://github.com/bibanon/tubeup/blob/b18c8175f2a2ed4de8f114e2dd5f2325c532b241/tubeup/TubeUp.py#L297-L311

3. Similarly, why upload the description, infojoson and annotations when this data is already present in `metadata`?
https://github.com/bibanon/tubeup/blob/b18c8175f2a2ed4de8f114e2dd5f2325c532b241/tubeup/TubeUp.py#L315

4. In #146, is there any reason to not completely strip out the URL instead of just redacting the IP? The URL is useless without the IP after all. Also, there is no point in archiving the stream URL since it will expire after some time

**Comment by vxbinaca** [comment]
1. Thats the standard for how the metadata is seperatly archived from the items metadata.
2. Thats the way it was done before I touched the code, way back in like 2012 I think, based off reccomended flags for youtube-dl. It doesn't hurt and it's a few bytes of space.
3. Just in case.
4. You mean the URL to the video asset/VOD? I don't want to get into a endless series of arguements about what is and isn't saved. I think the information redaction reason is a good one to snip out stuff, but since the solutions people put forward are lackluster, use a VPS.

Ya'll seriously shouldn't be dumping channels from your desktops. And the 429 errors aren't coming from Youtube or others (instagram is far more agressive) looking up who;s dumping, they come from AI detecting bot-like behavior.

**Comment by brandongalbraith** [comment]
@vxbinaca if @pukkandan wants to submit a PR to cleanup some of these loose ends, I'm up for it! I think there's value in simplifying without removing any functionality.

**Comment by vxbinaca** [comment]
If we're going to be REGEXing through JSON, I want the separate description and annotations as a backup. With annotations some metadata was generated, and I'm not discarding it. The functionality may work on other sites ,we don't know, I'm for leaving those flags as they are. 

I'm open for a compelling reason to get rid of them. Just 'it's in the JSON' isn't enough.

**Comment by pukkandan** [comment]
> The functionality may work on other sites ,we don't know, I'm for leaving those flags as they are.

No, it won't break. The writedescription and similar options of youtubedl just writes the corresponding entry in the infodict to file. So if it doesn't exist in infodict, it won't be written to file. But i you want to keep it, I have no issues. I was just curious.

> If we're going to be REGEXing through JSON

I was thinking of NOT downloading the infojson and only using the info_dict object. That would have been much easier to work with for making any changes.

But since you guys want to keep both metadata and infojson, then using `json.loads` and regexing in known fields might be a better alternative than #146 depending on your priorities. This method will only remove the IP from known places (like youtube stream URL). This will ensure that there are no false positives, but the downside is that personal data from other extractors will not get redacted.

#146 on the other hand, regexes through the whole JSON for IP addresses. This ensures that no IP data gets left behind, but the downside is that anything that looks like an IP will also get removed. For example, if the title has `1.2.3.4`, it will get redacted

**Comment by vxbinaca** [comment]
>>I was thinking of NOT downloading the infojson and only using the info_dict object. That would have been much easier to work with for making any changes.

The problem with that i sites like Instagram with two videos in a single URL, both rip without the creator name and instead a generic failsafe of "tubeup.py" is used. I believe the actual creator name is journaled in the JSON.

Again, why get rid of it? Tubeup used to dump metadata into the video title, so I removed that from being included because it's in 3 other places and messes up presentation.

Getting rid of aspect of metadata because your IP shows up in the metadata is really overkill. 



Really close to saying the VPS/privacy thing. I despise this issue both that it exists and the hamfisted 'solutions' proposed.

**Comment by vxbinaca** [comment]
@pukkandan The likes or other types of data are stored in JSON. Also other information IA doesn't have the ability to accept. If we ditch JSON all that goes away.

Not to mention the internet is larger than YouTube. Other extractors deal with other types of data that end up going into JSON.


Seems really drastic to not use a VPS. Also you guys are getting 429s due to YT monitoring how their site is used. I have my suspicions about what triggers it and a fix might break site support which is unacceptable. Remember the internet is larger than YouTube.

That's if I'm reading your issue correctly, that you want to ditch JSON in favor of the lesser Metadata fields on IA.

**Comment by pukkandan** [comment]
> I was thinking of not downloading the infojson and only **using the info_dict object**. That would have been much easier to work with for making any changes.

I think you misunderstood me. I was not saying the information should be thrown away, only that the same can be obtained directly from the `info_dict` that youtube-dl provides. 

Anyway, It doesn't matter. The regex used by #146 is a more rigorous approach than what I was intending to use.
