### ISSUE TITLE
How to pass extra commands to youtube-dl?

### ISSUE THREAD

**Issue by mattl** [bibanon/tubeup#173]
I'd like to be able to periodically run tubeup with the youtube-dl `--dateafter` command.

ie. `youtube-dl --dateafter now-7days` so I can archive channels that specialize in weekly drops of new videos that could be archived.

**Comment by brandongalbraith** [comment]
@mattl I believe that the tubeup option `--use-download-archive` meets your use case needs. Please let me know if it does not work as expected. I will leave this issue open for a bit until I hear back.

**Comment by vxbinaca** [comment]
I agree the download archive flag is best because it won't miss anything. You can print out the channel IDs previous to thedate you want with youtube-dl, then journal them in `~/.tubeup/.ytdlarchive`. After that you just keep ripping that channel and it only gets videos after that date.

**Comment by mattl** [comment]
Hm, is that a file I should already have on my system? I've got a few videos and jpg (plus a bunch of json) files in .tubeup/downloads/

**Comment by brandongalbraith** [comment]
@mattl That file will be present if you've uploaded any content to the Internet Archive successfully. It is a hidden file due to it starting with a period. I should probably add a command line argument to tubeup to dump that file to the console (for review or redirection).

Running `cat ~/.tubeup/.ytdlarchive` from a terminal on your workstation should output the file contents to your terminal window.

**Comment by mattl** [comment]
Hm, is it a relatively new thing? I'm going to update tubeup...

**Comment by mattl** [comment]
Okay, I updated from 0.19 to 0.26

Now I'm getting this when I run `tubeup https://www.youtube.com/watch?v=RJWPNmDuktM`

An exception just occured, if you found this exception isn't related with any of your connection problem, please report this issue to https://github.com/bibanon/tubeup/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tubeup/__main__.py", line 96, in main
    for identifier, meta in tu.archive_urls(URLs, metadata,
  File "/usr/local/lib/python3.8/dist-packages/tubeup/TubeUp.py", line 381, in archive_urls
    identifier, meta = self.upload_ia(basename, custom_meta)
  File "/usr/local/lib/python3.8/dist-packages/tubeup/TubeUp.py", line 332, in upload_ia
    parsed_ia_s3_config = parse_config_file(self.ia_config_path)[1]['s3']
TypeError: 'bool' object is not subscriptable

It also seems like the ia.ini moved from .config/ to .config/internetarchive/

**Comment by vxbinaca** [comment]
First, please indent your comments that have text output properly. You just deleted all the text in the issues template instead of hitting X in the boxes.

Downgrade `internetarchive` to 2.0.3 and your uploads will work again. This is a known issue right now. Since you don't read the issue template, that among other things tells you to search for duplicate issues I'm closing this issue.

**Comment by mattl** [comment]
I’m posting on mobile. I’m not sure I get those boxes.

**Comment by mattl** [comment]
I did not.

**Comment by mattl** [comment]
👍  will do. Just trying to see if my thing will work.
