### ISSUE TITLE
Bug report: I broke the unite tests just editing the issues template

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#175]
@brandongalbraith  I know I'm breaking our own rules here, but editing the MD file for the issue template broke github tests. I didn't think you could do that just editing a file not related to code. The linting is fine.

I've gone ahead and switched downloaders again this time permanently no going back, and locked `internetarchive` at a stable version until we can investigate. But I've triaged the code to get it functional again. 

Could you tell me what I did wrong with editing the issues template?

**Comment by brandongalbraith** [comment]
Acknowledged, should be a quick fix whatever broke.

**Comment by brandongalbraith** [comment]
@vxbinaca Tests failed because `ia` library wasn't pinned to 2.0.3 (which is currently is with https://github.com/bibanon/tubeup/commit/652ce7be13e6d7934ac10114872358f35c31d19d) and 2.1.0 introduced a breaking change when parsing IA S3 API creds:

```
        # Parse internetarchive configuration file.
>       parsed_ia_s3_config = parse_config_file(self.ia_config_path)[1]['s3']
E       TypeError: 'bool' object is not subscriptable

tubeup/TubeUp.py:337: TypeError
===================== 2 failed, 22 passed in 3.62 seconds ======================
Error: Process completed with exit code 1.
```

Closing as this is tracked by https://github.com/bibanon/tubeup/issues/172.

**Comment by vxbinaca** [comment]
Oh shit I didn't think about that
