### ISSUE TITLE
Feature Request: add support for live chat 

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#199]
yt-dlp uses it and you should support live chat too, as it is crucial for stream archiving. If it takes a long time, add a flag for it at --get-live-chat .

**Comment by vxbinaca** [comment]
Live chat is not a language, it could be added and eventually IA has a way to deal with it later down the road. I'll look into it tonight.

**Comment by vxbinaca** [comment]
So yt-dlp says it treats live chat as a subtitle:

`Youtube live chat (if available) is considered as a subtitle. Use --sub-langs all,-live_chat to download all subtitles except live chat. You can also use --compat-options no-live-chat to prevent live chat from downloading`

We get all subs. So this should be gotten already. You're consistently asking for thing we already do. Are you making these issues about live chat and auto subs because IA doesn't display them? Because if so this is on them.

**Comment by vxbinaca** [comment]
I think I may need to push a new version now, yt-dlp has started to drift in terms of library calls. I think. Lemme check much deeper.

**Comment by vxbinaca** [comment]
Actually I want to go and look at all the download/extractor opts now and make sure they haven't changed.

**Comment by vxbinaca** [comment]
Okay I can do this, gimme a bit to test

**Comment by upintheairsheep** [comment]
K sorry

**Comment by vxbinaca** [comment]
Upgrade to the latest version and try it.

**Comment by vxbinaca** [comment]
I'm not liking the new flags I wanna revert the codebase, and posh 0.00.30 which is really 0.00.28 and tell @upintheairsheep from now on if he wants extra subtitle functionality to submit a PR. Every time I try to play with a downloader arg it breaks the repo, and fixes to tests (which are becoming more trouble than they're worth) don't fix the tests even though I mirrored over the changed I made to the main code base.

**Comment by vxbinaca** [comment]
I am reverting the repo and pushing 0.00.30. @upintheairsheep If you want a feature from now on do not ask us, submit a PR.
