### ISSUE TITLE
On the privacy disclaimer

### ISSUE THREAD

**Issue by SuperSonicHub1** [bibanon/tubeup#211]
yt-dlp by *default* does not include "_filename" or any IP addresses in its `.info.json` files due to [`--clean-info-json`](https://github.com/yt-dlp/yt-dlp#filesystem-options). You guys should feel free to remove the foreboding warning from your README.

**Comment by tim78245** [comment]
Not true. tubeup does not sanitize IPv6 addresses.

**Comment by vxbinaca** [comment]
> 

take that up with yt-dlp

**Comment by tim78245** [comment]
> take that up with yt-dlp

Nowhere did I say you had to fix yt-dlp's problem, only that the information in this issue that was used to remove the disclaimer was false.

Ultimately though since tubeup is the one uploading people's IP addresses to the internet archive I think the privacy disclaimer (that they should either fix it themselves or not use tubeup at all) should be added back until it's actually not a problem.

**Comment by vxbinaca** [comment]
> Since tubeup is the one, unintentionally, uploading people's IP addresses to the internet archive I think the privacy disclaimer (that they should either fix it themselves or not use tubeup at all) should be added back until it's actually not a problem when using tubeup.

You're saying v6 addresses are missed by yt-dlps JSON sanitize? Can you link a item that displays this?

**Comment by tim78245** [comment]
> You're saying v6 addresses are missed by yt-dlps JSON sanitize? Can you link a item that displays this?

You know I think I got it wrong, yt-dlp seems to be missing entire fields rather than merely IPv6 (mine was captured in IPv6, so I thought it was just IPv6).

Here's three random examples I found by searching `(scanner:TubeUp Video Stream Mirroring Application 0.0.35)`, and then sorting by published:

https://archive.org/download/youtube-diPdOYG_f1Y/diPdOYG_f1Y.info.json
https://archive.org/download/youtube-VZj4bLXz8Rc/ITZYITZY_EP123%20--%20VZj4bLXz8Rc.info.json
https://archive.org/download/youtube-zmvNwu8_dqk/zmvNwu8_dqk.info.json

These so happen to be just the first three I tested, the only methodology I had trying to find three different uploaders, so I imagine trying any of the recent ones will lead to the same result.

(you can find the ip addresses by ctrl+f `ip=`).

**Comment by vxbinaca** [comment]
We've had this discussion before with Pukaden, yt-dlps maintainer. To scrub those URLs may have false positives for the items description. Meaning taking it out of URLs.

Please take this to Puka, have him drop any `ip` metadata from the JSON. The extracted video data links are another story. 

If you want privacy, use a VPS or VPN.
