### ISSUE TITLE
Support arbitrary options from yt-dlp

### ISSUE THREAD

**Issue by SuperSonicHub1** [bibanon/tubeup#212]
Multiple issues (#186, #189) ask for the ability to use existing yt-dlp options with Tubeup. These issues, and any future ones, can be closed by using yt-dlp's [argument parser](https://github.com/yt-dlp/yt-dlp/blob/2ae778b8fc56087462e48d1e31208c2a398409c1/yt_dlp/__init__.py#L636-L834).

Here's some example code from a project I worked on the other day:
```python
from argparse import ArgumentParser
from yt_dlp import parse_options

parser = ArgumentParser()
parser.add_argument('args', nargs='+', help='yt-dlp arguments')
args = parser.parse_args()
parser, opts, all_urls, ydl_opts = parse_options(args.args)

print(ydl_opts)
```

Of course, `parse_options` is not documented, but the function hasn't moved nor has its signature changed dramatically in years, so I think it's fine to use.

I'd be happy to do this myself; just making an issue so I can get two thumbs up from the maintainers.

**Comment by vxbinaca** [comment]
Internet Archive needs predictability based on version numbers as to what options are default run. It's a all or nothing proposition. We can't have one user obsessively scraping every metadata in all formats of a video where most users on the same version just use the defaults, vice versa, or anything in-between. There'd be no consistency because one user or set of users would do it one way and then this breaks scripts or mass edits Archive needs to make to fix items, EX: Twitch uploads or certain sites with bugged extractors. EX: forcing SRT subtitles or some other funky format, or forcing some odd format in videos that doesn't derive correctly because one user incorrectly - and they'd be incorrect here - think the defaults don't get the highest quality video and audio streams (YTDL and YT-DLP use the best of both streams and mux accordingly, and this has been the case since 2012).

If you think Tubeup doesn't include something or should be changed, discuss it with the maintainers. Bring it up here. Stop asking for variables you set yourself.  

So IA can say "oh hey looking at the development of Tubeup, we know version 0.00.59 had a weird bug in it based around either something they did or a YT-DLP issue and we can write scripts to fix that".

Maybe instead of blindly asking for all args out of yt-dlp, maybe talk about your needs and they can be baked in as flags that IA can handle in the future. Remember you're setting the record with these uploads. 75 percent of the people coming here asking for this don't realize the implications of what they're asking for.

**Comment by vxbinaca** [comment]
>#186

live start rips are experimental and not suitable for daily driving

>#189

In my testing this was a modest speed increase on Twitch, where you'd really want to test something like this. Trouble is setting that may get your box banned (you are using a box and not your desktop, correct?). Instagram has heavy rip throttling/stopping.

Best to look like a browser looks like, and yt-dlp/YTDL have the best balance when it comes to things like URIs and user-agents. Typically - except with Instagram - you don't trip any kind of system that looks for rips with the defaults.

**Comment by SuperSonicHub1** [comment]
Yes, I understand the importance of getting archival right the first time; I've made multiple contributions to IA before.

If the focus of this project is stability, I can understand why you'd be hesitant to open the floodgates; I'll open up issues for the groups of and individual options I need.

**Comment by vxbinaca** [comment]
Sure post away. See you then. Thanks.
