### ISSUE TITLE
Use different directory on Termux

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#230]
For people that rip endangered media via Termux (the qin guy rips mainly with his phone), please change the default “cache” directory (.tubeup) to /storage/emulated/0/.tubeup/ . Then you can use a file manager to delete unnecessary cache.

**Comment by upintheairsheep** [comment]
and move the .tubeup folder from termux’s home directory to the shared storage too when updated.

**Comment by upintheairsheep** [comment]
Also don’t forget to add the .nomedia file.

**Comment by vxbinaca** [comment]
We're not optimizing Tubeup for mobile devices. You can configure Termux to change directories. You rip channels or long videos at your own risk. Please acquire a desktop or a decent VPS with 100GB of disk space on a single disk, not a budget VPS.

We have no control over Termux.

**Comment by gabldotink** [comment]
You can use the following command:
`mv $HOME/.tubeup/ /storage/emulated/0/.tubeup/ && ln -s /storage/emulated/0/.tubeup $HOME/.tubeup`
to set this up. `tubeup` will write data to the directory successfully, and you can access the files from both Termux and your preferred file manager. Remember that you'll need to turn on hidden files for your file manager if you haven't already.

**Comment by vxbinaca** [comment]
Get a real VPS ,not one you got on a deal that has limited storage, something where ~/home is at least 100GB. We're not targeting Tubeup for moible phones. You use it at your own risk on mobile phones. VPS are best suited for ripping.

**Comment by vxbinaca** [comment]
a VPS or dockerized setup is faster too, mobile internet connections have latency due to their wireless nature. Uploads and downloads go after on a dedicated device thats hard wired to the internet. Even on 5G my desktop beats my phones that have Termux installed.

Termux on the Play store appears to be abandoned, it's unwise to point to it as a solution because it requires third party app stores with extra setup to use. VPS or docker on something you rent or control is best.

**Comment by gabldotink** [comment]
I am aware you're not optimizing `tubeup` for platforms it wasn't intended for. I was offering a simple workaround for a simple problem, which you don't have to approve of or anything.

A VPS is a great way to use `tubeup`. And if that's your recommended way, then that's great. But in the end, any device with Python and an internet connection can run it. And there's nothing wrong with that. As the license says, the software is distributed with no warranty. However you recommend the use of the software, there are going to be users who, _entirely at their own risk_, use the software in a way you don't intend or recommend.

My reply did nothing but help a user who wanted to use `tubeup` in a non-standard configuration.

That's the last thing I'm going to say about the whole Termux thing. Some people will use it with Termux, and they're not your responsibility.

**Comment by vxbinaca** [comment]
Termux not getting updates on the Play store anymore is a good reason to discourage mobile use. This ontop of Apple having storage limits for apps. I'll happily discourage Desktop use when Linux no longer gets updates. It is currently not reliable or relatively easy to do tubeup on mobile.

**Comment by gabldotink** [comment]
OK, fine. One more thing about Termux.

The Play Store version doesn't get any further updates, and the Termux developers actively discourage installing from the Play Store. The latest versions are available on the third-party app store F-Droid. You can download F-Droid [here](https://f-droid.org), then you can search for "termux" and install the latest version.

There. Now I'm done.

**Comment by vxbinaca** [comment]
Right but when people on Reddit or blogs or videos say "go install Termux to use Tubeup" people will try for the Play store one. Also IIRC it's due to some Android 12 policy that Termux isn't being updated.

Someone will slip up and not tell people to install F-Droid, and then wonder why - and this is gonna happen pretty soon - Python is out of date and won't run Tubeup. Then we get issues. This with Apples app storage limits is why it's easier to discourage mobile use.

**Comment by gabldotink** [comment]
Noted.
