### ISSUE TITLE
Change exception error

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#240]
Please change the exception error message to tell to report downloading problems to yt-dlp’s issues and not over here, and report issues if related to after the download finished.

**Comment by vxbinaca** [comment]
Copy and paste error so we can see if it is ours or yt-dlps.

**Comment by vxbinaca** [comment]
`Max retries exceeded with url: /metadata/youtube-_ZmmWU_XLNo (Caused by ResponseError('too many 502 error responses'))"), 'https://archive.org/metadata/youtube-_ZmmWU_XLNo')`

Archive.org is either being swamped with item lookups or they're undergoing server maintenance (hard drive change or server repair or additions). 



@upintheairsheep I want you to read the issue submission guidelines from now on and follow them. Put Xs in the boxs. All of them. Check your software is up to date. Provide a full un-redacted URL **AND** full terminal output of what you're trying to mirror. **Indent your terminal output with Github markdown properly**. Check [Internet Archive twitter account](https://twitter.com/internetarchive) for announcements about outages or planned maintence.

If you fail to do any one of these I will close and lock your issue from now on. **If you clear out the submission text and just write whatever, I will close and lock the issue on sight.**

**Comment by vxbinaca** [comment]
The entire site is down for me right now. They're doing maintenance or had a power outage.

**Comment by vxbinaca** [comment]
I will say, this is exactly the third time since all those years ago where when I implemented the upload re-tries that it's exceeded 9001 retries. The safety feature worked. In fact it worked a lot of other times when there was brief outages that only did ~1500 retries. Amazing. @brandongalbraith .

So it's failing on the searches, so the front end systems must be out because I'm not even getting pings from them.

**Comment by vxbinaca** [comment]
Actually this is a failure mode I didn't foresee. Theres retries for uploads but nothing for searches and it breaks Tubeup.

**Comment by vxbinaca** [comment]
Do we need to though? If the default of searches is run, so no disabling the search with the flag, but if it can't search it still doesn't download anything it would seem. If it could search it would hit retries, or S3 throttling or any other thing. If search is down, uploading is likely down too.

So if it doesn't download anything we should be good. You'd wait for full services to return.

**Comment by vxbinaca** [comment]
```
   raise type(exc)(error_msg)
requests.exceptions.ConnectTimeout: Error retrieving metadata from https://archive.org/metadata/youtube-3LsLMO9r1cQ, (MaxRetryError("HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: /metadata/youtube-3LsLMO9r1cQ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6d4db29dc0>, 'Connection to archive.org timed out. (connect timeout=12)'))"), 'https://archive.org/metadata/youtube-3LsLMO9r1cQ')
```

Wait what's connection timeout=12? Can we increase that or is it baked into `internetarchive`?

**Comment by vxbinaca** [comment]
@upintheairsheep https://twitter.com/internetarchive/status/1562637688918142976

**Comment by vxbinaca** [comment]
yeah thinking back on this, this wasn't really a issue because IA was totally out for that period. like you want it to fail on checking for items. That prevents downloads.
