### ISSUE TITLE
Comments are not downloaded with --get-comments if --ignore-existing-item is not enabled

### ISSUE THREAD

**Issue by gabldotink** [bibanon/tubeup#255]
**Checklist**

# If you just delete all this text and post a issue it will be closed on sight.

Carefully read and work through this check list in order to prevent the most common mistakes and misuse of tubeup, put x into all relevant boxes (like this [x])

- [x] I have fully updated tubeup, youtube-dl and internetarchive along with their associated dependencies.
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the issues (closed or open) for similar bug reports including closed ones
- [x] I am not submitting a bug report about S3 timeouts (we have no control over Internet Archive outages or per-user throttling)
- [x] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure maintenance that would affect performance of uploads.
- [x] **(attached as files below due to size)** I have properly indented [with triple backticks before and after the console output](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

**Dependency versions**

Please provide version information from core dependencies:

`ia --version`
`3.0.2`

**Expected behavior**
Download comments with `--get-comments` whether or not `--ignore-existing-item` is enabled.

**Additional context**
Sorry to submit another bug so soon. As far as I know, this issue was introduced in the newest version, `0.00.34`.

Running a command with `--get-comments` but without `--ignore-existing-item` does not download comments. Adding `--ignore-existing-item` causes it to download comments, in addition to the flag's normal behavior.

Logs (note that these contain ANSI color codes and some other special characters):
`tubeup --debug --get-comments https://www.youtube.com/watch?v=NrhteGYYuuY` [no-ignore.log](https://github.com/bibanon/tubeup/files/9894665/no-ignore.log)
`tubeup --debug --get-comments --ignore-existing-item https://www.youtube.com/watch?v=NrhteGYYuuY` [with-ignore.log](https://github.com/bibanon/tubeup/files/9894668/with-ignore.log)

Video to download/upload: [https://www.youtube.com/watch?v=NrhteGYYuuY](https://www.youtube.com/watch?v=NrhteGYYuuY)
IA item uploaded to: [https://archive.org/details/youtube-NrhteGYYuuY](https://archive.org/details/youtube-NrhteGYYuuY)

Tell me if you need anything else. Thank you.

**Comment by vxbinaca** [comment]
@mrpapersonic You need to come up with a better fix than a FlexSeal fix, adding the first check canceles out the comment stans comment rips.

@gabldotink Stress test this version because when I cut a new version I want this problem squashed. Either that or you'll have to go pester IA to do a better job at comment ingestion because we ain't it if this can't be fixed.

**Comment by vxbinaca** [comment]
If none of you can fix this I vote to remove or disable `--get-comments` because this flag is more trouble than it's worth for reason previously stated.

**Comment by gabldotink** [comment]
OK. I don't know much Python, but I'll try messing around to see if I can figure out more about the problem.

I doubt it's a problem with the Internet Archive, since all it should be doing is uploading the existing `info.json` file along with other metadata. I'll see, though.

**Comment by vxbinaca** [comment]
>OK. I don't know much Python, but I'll try messing around to see if I can figure out more about the problem.

Don't. Don't do that. You've admitted you don't know what you're doing so leave it at that. Let someone else here do it or I'll just cut out the `--get-comments` PR of the code base and live with telling you to go about another way of saving your comments snapshots.

It's not IAs problem it's tubeups. The FlexSeal fix don't carry over the flags from the first pre-check so this breaks other flags too.

**Comment by gabldotink** [comment]
> Don't. Don't do that.

Why not? If I don't figure out anything I don't figure out anything. Literal worst case scenario is that I get confused and give up.

I can always just use an old version of tubeup with comments as well.

**Comment by gabldotink** [comment]
I'm not going to argue with you anymore, because I never should have. I apologize, as I already have multiple times.

What I was referring to with "old version" was a version that supported comments while the issue was possibly fixed (it could get put on the backburner, that would be fine &mdash; I would even be willing to slowly work on it myself). I respect your opinion to get rid of comments if they are too much of a hassle. It's just that if you are removing comments in a future version, I would rather use an old version with comments, even if it is imperfect, because the problem does have workarounds. There's no shame in removing a feature and adding it in back later once it's stable, too.

Once again, if comments are gone now, comments are gone now.

**Comment by vxbinaca** [comment]
Well other devs don't like the feature because it's a constantly broken timesink. My advice: use yt-dlp to scrape the comments, comments are a website element and not a video element this is a video tool. Do it on your own.

If one of us can fix it this one last time, fine, but I don't think thats going to happen. Tubeup is too complex as a tool and this is a straw that broke the camels back thing. 

Do your own comments ripping outside tubeup is my suggestion. This feature sucks it's broken and only you use it, not the hundreds of other people who use this tool. It's a hair away from breaking the rest of the flags I don't know how collections and other metadata stuff isn't broken right now. Thankfully it's only comments in this one specific scenario.

**Comment by gabldotink** [comment]
Once again, if you would like to remove the feature until it's stable, it's your call.

**Comment by vxbinaca** [comment]
I want to remove the feature entirely forever because comments are outside of the scope of the tool AND it's broken AND people have tried to rehab this feature that only YOU use. And no it isn't helping you that you said I'm wrong on so much when you're fresh and new and don't know *any* python and are telling me I'm doing my job wrong (which i've been doing 7 years btw).

You know whats easier than learning python and doing a bunch of trial and error PRs that may or may not break a tool others rely on? You cracking open yt-dlps README and learning the flags, and then just doing the rips of comments yourself and putting them into a collection. If you think IAs scrapes suck tell them, and take up the slack like I did. I came in and started doing fixes ages ago to the best of my abilities.

Comments have zero value in relation to video, and this is a video tool, and this feature is a hair away from breaking other flags that people who care about video rely on.

Read YT-DLPs readme, learn how to scrape comments with it. Do a serperate collection on IA, I can point you to the right place.

**Comment by gabldotink** [comment]
Please stop. You have already told me this. It is not helping.

**Comment by vxbinaca** [comment]
Apparently I have to repeat myself.

I'll give you hundreds of thousands of youtube video IDs maybe 20 percent are gone. I'll write a script to scrape their comments to JSON files. I will lay out a way for you to do the ripping yourself and hopefully you can figure it out. It would only take me 5 minutes to do this in VIM and most of that is testing to see if it'd work on one videos comments. If you are this afriad of losing history I can set it up for you outside this tool.

I do not want this feature in tubeup, and do not want it on by default so others do what you should. yt-dlp is simple to understand but I can get you started on mass comment scrapes.

**Comment by gabldotink** [comment]
I appreciate the offer, but I can figure it out myself. I have experience with CLIs and Bash.

This is the last message I'm going to send on this thread. Close the issue, remove `--get-comments`, I don't care. Do what you need to. Thank you for working so hard on this project.
