### ISSUE TITLE
Should we turn off writing the description due to it already being in the info.json?

### ISSUE THREAD

**Issue by upintheairsheep** [bibanon/tubeup#268]
I've discovered a long time ago that the description was already in the .info.json file. Additionally, it is also in the IA metadata. The tiny description file also takes a long time to upload due to the IA's infrastructure, the discussion should begin, should we not write the description file?

**Comment by vxbinaca** [comment]
No because the info.json was messed up once in youtube-dl, but the separate description it was saved with the proper indentation and the full description contents.

If a future bug is introduced from say, IP cleansing, the description would live on in the separate file. it's a few kilobytes per item. Over 2.5 million items it's....what I can't math so like a gig across all of IA. But the advantage is you have a confirmed separate copy of the description.

A long time to upload? I don't see it. Like a second to upload. How long does it take for you and what environment are you using that gets these slow speeds?
