### ISSUE TITLE
Upgrade yt-dlp ASAP to at least 2023.07.06

### ISSUE THREAD

**Issue by vxbinaca** [bibanon/tubeup#293]
[CVE-2023-35934]([https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-35934)

It's unsafe to use `--cookies` below the version of yt-dlp cut yesterday.

**Comment by vxbinaca** [comment]
When users upgrade tubeup it should pull deps too.

**Comment by vxbinaca** [comment]
I've been thinking about switching yt-dlps downloader to curl, but then it's one more dep, and curls problems become our problems. Also theres no known benefit to measure against.

**Comment by gamer191** [comment]
> When users upgrade tubeup it should pull deps too.

I believe you can set a minimum versions for dependencies, and if a lower version is installed pip will automatically update that dependency

I'm not sure if you'd want that though, it could cause dependency hell, and it would also prevent python 3.6 users using this since yt-dlp's latest version requires python 3.7+
This program seems to require 3.8+ though, so that shouldn't be an issue I guess

**Comment by vxbinaca** [comment]
> I'm not sure if you'd want that

Only for maintainability reasons would I not do it. It's the users responsibility to keep yt-dlp up to date.

> python 3.6 users

they can perish
