### ISSUE TITLE
Add a "local mode" to assist in uploading from disk

### ISSUE THREAD

**Issue by zoktiik** [bibanon/tubeup#318]
When it comes to online video archival, it seems that the Internet Archive is primarily interested in storing videos of channels which have a decently credible threat of possibly being deleted in the near future. For channels and videos which don't fit this criteria, staff have suggested to uploaders that they first save the videos to disk for later upload in the event that they become unavailable. However, I am not yet aware of any tool which would assist in automating the process of "restoring" from those user backups. Tubeup has the ability to automate checking for duplicates, parsing info.json to IA metadata, and creating new items via the `internetarchive` tool, all of which would be very useful for mirroring on IA post-deletion.

Is there any possibility that this could be added as a feature? I don't foresee it being necessarily easy or straightforward to implement, but I feel that the potential usefulness of this addition might justify the ideaguy proposal.

The following is a list of thoughts about a possible implementation:
- Required: info.json, video id in filename (in brackets per default output template, or user-specified custom regex) for both video and metadata files
- Recurse through directories, might require an appropriate argument to be passed?
- Uploaded files use the standard Tubeup file naming template, either by copy-and-renaming to a temporary directory or, if `internetarchive` allows, uploading from the original directory's files to the proper filename and directory structure
- Parse info.json for potential indicators of a bad upload and give a warning/error, i.e. low resolution, low-quality `-f`ormats, etc.
- Check if the video is still alive, either skip the video ("local-only") or download then upload the video (how Tubeup operates currently)

**Comment by mrpapersonic** [comment]
This is pretty out of scope for tubeup's concern, but portions of tubeup's main class can be used to do this exact thing (I've done it before, but I don't have the code anymore). Just make sure when they're uploaded that they're not being put under the tubeup scanner ID (i.e., by retrieving the metadata from tubeup, editing that value, and passing the result to internetarchive)

**Comment by vxbinaca** [comment]
@zoktiik Tell Jason Scott he's wrong about storing videos locally - because on this issue he is and he doesn't know everything the difference between him and I is I can admit when I'm wrong. If IA staff are complaining about you usage the modify your behavior. No, a long issue isn't going to sway me. We've treaded over this three times why it's a bad idea, I've discussed it in private with Jason twice. Multiple BibAnon devs don't want this feature.

It's code complexity sucks. Tubeup is becoming more and more complex for more and more niche reasons that less and less people use. It's supposed to be a quick rip tool. People want it do do live videos, but it can't because of how yt-dlp works. People want local storage and now to parse your collection of videos you illadvisedly put into folders by creator (pro-tip: just dump your haul without directories into `~/.tubeup/downloads/`, and before doing all this journal the IDs, you'd need to rip it with the metadata and in the output format Tubeup uses).

The feature you want is open to abuse because the videos could be altered, downgraded in quality because the jerk storing them compressed them to save a hundo on a 2TB SSD, or edited them to alter history, edited the metadata whatever.

It's a bad idea. Tell Jason this, tell everyone in Archive Teams IRC this, tell the Discord too, run through the streets screaming it to random people like the end of _It's A Wonderful Life_ so everyone knows to stop coming here and stop asking for delayed uploads.

**Comment by zoktiik** [comment]
For the record, it wasn't Jason Scott. It was an email reply I got from someone working at the Internet Archive. I haven't been in the ArchiveTeam IRC/Discord either; I assume both Jason and ArchiveTeam might disagree with that email.

Thank you for the tip; if that `~/.tubeup/downloads` trick doesn't work for whatever reason, I'll have a look at the code and possibly come up with a solution similar to what @mrpapersonic mentioned.

**Comment by vxbinaca** [comment]
> For the record, it wasn't Jason Scott. It was an email reply I got from someone working at the Internet Archive. I haven't been in the ArchiveTeam IRC/Discord either, and I assume both Jason and ArchiveTeam might disagree with that email.
> 
> Thank you for the tip; if that `~/.tubeup/downloads` trick doesn't work for whatever reason, I'll have a look at the code and possibly come up with a solution similar to what @mrpapersonic mentioned.

you just put the URL or channel in without stripping the filenames only down to the `videoID` right? It still has words in it from the titles right? Theres your problem.

Perhaps use the tool less, or I could tease out what the command would be to duplicate Tubeups style of rips.
