### ISSUE TITLE
TypeError: send() got multiple values for keyword argument 'timeout'

### ISSUE THREAD

**Issue by ohhdemgirls** [bibanon/tubeup#41]
```
:: Uploading /root/.tubeup/downloads/Pong_AI_with_Policy_Gradients-YOW8m2YGtRg...
Traceback (most recent call last):
  File "/usr/local/bin/tubeup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 263, in main
    identifier, meta = upload_ia(video, custom_meta=md)
  File "/usr/local/lib/python3.5/dist-packages/tubeup/__main__.py", line 208, in upload_ia
    item.upload(vid_files, metadata=meta, retries=9001, request_kwargs=dict(timeout=9001), delete=True)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 830, in upload
    request_kwargs=request_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/item.py", line 690, in upload_file
    **request_kwargs)
TypeError: send() got multiple values for keyword argument 'timeout'

```

**Comment by vxbinaca** [comment]
**This is not a bug with tubeup**

Downgrade `internetarchive` to 1.5.0. The maintainer of `internetarchive` knows about this bug, the bug has been fixed but the package just needs to be pushed to pip.

'sudo pip3 install -U internetarchive==1.5.0' 

Your tubeup should work after this. I'm keeping this one open because you're the third to submit a bug about it. The probem is due to tubeup specifying a timeoput value and internetarchive 1.6.0 having a baked in value and they conflict.

**Comment by dkl3** [comment]
Ah good thing someone else beat me to this. I was just about to make a Github page on this.

**Comment by vxbinaca** [comment]
@ohhdemgirls @dkl3 @antonizoon 

Internet Archive has been updated to 1.7.0. Plese upgrade you setups by running:

`sudo pip3 install -U tubeup`

or if you're on a VPS without sudo access

`sudo pip3 install --user -U tubeup`
