### ISSUE TITLE
Check For Item In Internet Archive Prior To Performing Retrieval

### ISSUE THREAD

**Issue by brandongalbraith** [bibanon/tubeup#58]
The tubeup [readme](https://github.com/bibanon/tubeup#troubleshooting) mentions this:

> Obviously, if someone else uploaded the video to the Internet Archive, you will get a permissions error. We don't want duplicates, do we?

Attempted to archive https://www.youtube.com/watch?v=ARrNYyJEnFI, but was not aware it already existed as an item.

```
tubeup https://www.youtube.com/watch\?v\=ARrNYyJEnFI
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.6.3 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[download] 100.0% of 2.46GiB at  2.94MiB/s ETA 00:00
{'downloaded_bytes': 2637871187, 'total_bytes': 2637871187, 'filename': '/Users/brandon/.tubeup/downloads/Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-ARrNYyJEnFI.f299.mp4', 'status': 'finished', 'elapsed': 855.510488986969, '_total_bytes_str': '2.46GiB', '_elapsed_str': '14:15'}
Downloaded /Users/brandon/.tubeup/downloads/Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-ARrNYyJEnFI.f299.mp4
[download] 100.0% of 142.46MiB at  3.53MiB/s ETA 00:00
{'downloaded_bytes': 149377905, 'total_bytes': 149377905, 'filename': '/Users/brandon/.tubeup/downloads/Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-ARrNYyJEnFI.f251.webm', 'status': 'finished', 'elapsed': 40.32209777832031, '_total_bytes_str': '142.46MiB', '_elapsed_str': '00:40'}
Downloaded /Users/brandon/.tubeup/downloads/Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-ARrNYyJEnFI.f251.webm
 uploading Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-AR uploading Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-AR uploading Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-ARrNYyJEnFI.annotations.xml: [################################] 1/1 - 00:00:00
 error uploading Introduction_to_Investing_and_Finance_-_Lesson_1_by_Martin_Shkreli-ARrNYyJEnFI.annotations.xml: Access Denied - You lack sufficient privileges to write to this item.
```

Is it sound logic to check for an item with the `Originalurl` tag value set to the URL specified to retrieve and upload prior to the retrieval process? If so, I'll proceed with a fork->PR.

**Comment by vxbinaca** [comment]
I wasn't going to close this even though I read the email preview earlier today. Now that I see you're offering a PR, go for it. expect a back-and-forth prior to implementation though.

All you need to do is pre-process the URL to change:

`https://www.youtube.com/watch?v=ARrNYyJEnFI`

to

`youtube-ARrNYyJEnFI'

You're going to run into a few problems right away, I'm just warning you since I HEAVILY use this script and have either steered work or done the dirty work myself of improving it:

- You'd need to make it work for all sites Youtube-dl supports, not just youtube.
- Sometimes, capitalization is off in the item identifier versus the URLs videoID but they are spelled the same. This was a problem with Naomi "Sexy Cyborg" Wu's videos (I run her collection and my scripts are constantly looking for new vids from her.
- It needs to work with channels and playlists.
- Look-ups may become abusive, so I want it to journal the ID when `--use-download-archive` is called so it doesn't do a further lookup in the future. 

So PR away. If you're feeling extra generous #46 would enable everyone to do Twitter/Twitch videos.

**Comment by vxbinaca** [comment]
@brandongalbraith I merged your previous very helpful PR. Thanks for that.

**Comment by rudolphos** [comment]
>Look-ups may become abusive, so I want it to journal the ID when `--use-download-archive` is called so it doesn't do a further lookup in the future.

Doesn't work when using with youtube playlists

```
 sudo tubeup https://www.youtube.com/watch?v=...&list=...--use-download-archive
[2] 35
--use-download-archive: command not found
```

**Comment by vxbinaca** [comment]
@rudolphos *Uncensor your command output.* I've asked you to do this reaptedly on other issues. I cannot test what you hide from me. 

Turn off `--use-download-archive` for it to work on the playlist you've already ripped.

Also, this feature hasn't been implemented yet. It's a proposal.

**Comment by brandongalbraith** [comment]
@vxbinaca Have some time to pick this back up, and have put some more thought into it between creation of the issue and now. I think having tubeup build its local index of content that the Archive already contains is suboptimal (due to possible overloading of their search functionality), and would prefer either:

1. The Internet Archive generate an index on a schedule and provide that packed index for downloading by tubeup
2. I create a process to generate that index and provide it for scheduling

Either way, the end goal is to minimize load on Internet Archive infrastructure while still providing functionality to prevent downloading content that has already been archived.

**Comment by brandongalbraith** [comment]
Happy to pursue this route instead of my proposal 👍 Thank you!

**Comment by vxbinaca** [comment]
We should force use of `--use-download-archive`` for this proposed flag to ensure this doesn't check for every single video on a channel everytime someone runs this. I really do not want to stress IAs infrastructure. 

Also why not something simple like `--item-precheck` for this proposed flag? Less chance for typos.

**Comment by vxbinaca** [comment]
I like this idea and it should be enabled by default, however I'd like a flag to disable the checks. For safety purposes and because I'm a vigorous user of Archive.org and I really want to minimize my impact. What say you, brandon?

If anyone thinks my concerns are overblown, please chime in and I might change my mind.

**Comment by brandongalbraith** [comment]
Possible fix for https://github.com/bibanon/tubeup/issues/70
