### ISSUE TITLE
Add "version" prefix if current archive is low quality

### ISSUE THREAD

**Issue by mariomadproductions** [bibanon/tubeup#65]
Many YouTube video items are archived in low quality because they were archived using an old version of tubeup. Could a feature be added that detects if the current archive is in high quality and if it isn't, use a prefixed item name (e.g. "youtube-[id].1", "youtube-[id].2").

I am assuming that the current tubeup uses "bestvideo+bestaudio" or equivalent, as that seems to be the way to get the [highest quality download](https://www.archiveteam.org/index.php?title=YouTube#.28Manual.29_Recommended_way_to_archive_Youtube_videos).

**Comment by vxbinaca** [comment]
1. Your premise is wrong because youtube-dl for about the last 4~5 years - possibly longer - by default tried to achieve the highest quality version `-f best`.

2. We go a step further and use `bestvideo+bestaudio' for all sites but specifically youtube. I/we care about fidelity immensely. Fidelity is proffered over all other considerations (including speed because last week Youtube was punishing downloaders who grabbed separate audio and video streams with download dial-up speeds as punishment)

>Many YouTube video items are archived in low quality

Perhaps they were low quality to begin with? [Age tends to be an indicator of this.](https://archive.org/details/youtube-jNQXAC9IVRw). Virtually no one was using this script years ago, but I believe that in all of it's existence youtube-dl was using `-f best` as the default. Tubeups first ancestor was written in 2012.

3. We're accepting pull requests.

**Comment by mariomadproductions** [comment]
2. Does ``-f best`` actually give you the best video though? Doesn't it just give you a video that has "good" audio and video, but not the best of both (as that is impossible without merging two formats), like ``bestvideo+bestaudio``?
4. I did have a specific video in mind, but I realise now that I'm not sure how to tell if a video was uploaded with tubeup. How can I tell?

**Comment by vxbinaca** [comment]
>Does `-f best` actually give you the best video though?

Like 90 percent the absolute best. Very good but not quite archival quality. The best usually-muxable-as-MP4 copy. It depends on the video and what formats are available. I've noticed available formats change over time for certain videos which drop filesize over slightly over the age of the video but this could be due to numerous things.

You're talking about a tiny difference that bugs only people like me. Also, you'd have to control that item you want updated meaning you'd have to be the one who uploaded it.

Now that you mentioned it, when Tubeup was rewritten at some point after I stopped actively updating it because it was beyond my meager means, it appears `bestaudio+bestvideo` was removed. So I'm adding it back in and after testing I'll either push a new version or leave it as is.

**Comment by vxbinaca** [comment]
Turns out I never added it for `bestaudio+bestvideo`, but theres a serious downside to adding this and a ton of people will open issues bitching:

`ratebypass` in youtube-dl no longer works, so you get dialup speeds when downloading separate video/audio streams. Basically as fast as it takes to watch/listen to the video.

People *will* bitch about this. They will bitch up a storm. It also doesn't appreciably improve PQ/AQ in my tests. In fact it seems the earlier you rip a video, the better it will look. I've gone back and ripped the same video and see a 50mb drop in filesize on the same video at highest quality settings.

I also tried to implement subtitle conversion, and when it's done as a library call instead of a flag in a command it just doesn't work and does nothing, we're still getting VTT files uploading. So Archive.org will have to make a process to derive VTT into SRT.
