### ISSUE TITLE
License metadata

### ISSUE THREAD

**Issue by emijrp** [bibanon/tubeup#66]
Hello,

Some videos in YouTube have Creative Commons license. It would be great tubeup adds this info in IA items while uploading.

The metadata field for this in IA is "licenseurl", example (not a video though) https://archive.org/details/wiki-beethoven.wikispaces.com

Thanks

**Comment by vxbinaca** [comment]
Hello and thank you for initially writing Tubeup. This wasn't well documented but you can pass `internetarchive` flags and insert metadata into the item Tubeup creates.

Use this example flag to achieve your goal:

` --metadata=licenseurl:http://creativecommons.org/licenses/by-sa/4.0/``

**Comment by vxbinaca** [comment]
Hey by the way @emijrp we've been having problems with metadata from sites like Facebook and Periscope killing uploads during the hand-off from `youtube-dl` to `internerarchive` at least I think it's something in the metadata I haven't had the time or skill to look into it but antonizoon added a bunch of safety settings to prevent this and they seem to not be there anymore since the rebase.

**Comment by emijrp** [comment]
> Hello and thank you for initially writing Tubeup. This wasn't well documented but you can pass `internetarchive` flags and insert metadata into the item Tubeup creates.
> 
> Use this example flag to achieve your goal:
> 
> `--metadata=licenseurl:http://creativecommons.org/licenses/by-sa/4.0/`

I think TubeUp could manage this in an automatic way. The license value is like uploader name or date, valuable metadata that should be magicly parsed and pasted in IA item.

If I give TubeUp a random list of YouTube videos, I don't want to provide metadata about license manually.
