### ISSUE TITLE
Uploading to D.Tube, PeerTube and Bitchute

### ISSUE THREAD

**Issue by DonaldTsang** [bibanon/tubeup#69]
It might be a good idea to not pull all eggs in one basket.  
Another good idea: IPFS the videos with https://mafintosh.github.io/playback/

**Comment by vxbinaca** [comment]
- Tubeups primary job is to preserve a video and it's metadata in a uniform way compatible with the Internet Archive. Tubeup is not a mirroring app, nor is Internet Archive a mirroring host. I do not treat it as such and you should not treat it as such. You should only use Tubeup for actual endangered content that exists nowhere else. 

For example: Forgotten weapons and tnoutdoors09 are high signal to noise ratio gun channels on youtube. Forgotten Weapons is uploaded in 3 places other than Youtube. tnoutdoors09 exists nowhere else but youtube. Youtube hates gun content and wants it gone. Therefor tnoutdoors09 should be preserved and Forgotten Weapons can live on on the other sites.

- The aforementioned sites don't provide for a lot of the metadata that Youtube provides, so it would be lost. This is unacceptable to an archivist.

- The Internet Archive has been around since 1996. It contains the corpses of Blip.tv, Justin.tv and many other failed experiments in competitors to youtube. What will likely happen is, pending youtube-dl support, I will end up going in and putting much of those sites on IA as I can.

Closing because your requests are not within our scope.

**Comment by DonaldTsang** [comment]
@vxbinaca I would like to make a claim that Internet Archive (as an organization) will also delete content, not for guns, but other "right wing" contents.  
http://archive.fo/t9MPS http://archive.fo/Og47p

**Comment by antonizoon** [comment]
Although I am also an IPFS proponent, you've got to understand what it really takes to replace the services we are uploading to (the Internet Archive or Google Drive). You have to either pay cloud providers (or with Filecoin and Storj, proof of storage miners), or you need to host a seedbox of your own on your own hard drives, whether it is peertube, ipfs, or whatever.

Much like the Cloud™, there is no magic going on that allows people to upload unlimited content that lasts forever without putting in your own resources or funds. Even though Google and Facebook currently operate this way, they make bank by having users pay with their data. By extension, these web giants donate massive amounts of funds to the Internet Archive for them to purchase Petaboxes daily, even if merely to get a tax deduction. As such, under property law, the one who pays the bills has full discretion over what is stored in their property. So, the solution is to take control over the hosting of that content yourself.

We can put all the facades we want on p2p protocols but much like torrents, someone must be seeding it or ponying up a monthly subscription fee. We know how YouTube works: a group of centralized Big data nodes and CDNs serve it to users, none of whom will serve the content again to others. We know how torrents work: the majority of users are leechers and do not serve again, with only a few seeds lingering out of motivation, of courtesy, or of obligation to private trackers, with the most reliable paying monthly for seedboxes.

Given this, you can now understand that you can actually just get started seeding these files in a much easier way than we are forced to with TubeUp, because you would be seeding it starting from your node. Just symlink the ~/.tubeup folder to a FUSE folder of your preferred p2p seedbox (as you would do for peertube), or just use any normal upload script (as would be done for IPFS) and upload it to your own node or someone else's node you pay for (on the centralized cloud, on encrypted Storj, on Filecoin).

**Comment by vxbinaca** [comment]
@DonaldTsang 

>IPFS

 So you want to put further barriers up to people getting access to the data? I kind of like easy streamable content. But it's easy for you to mirror my efforts and use that java player to run the files. Use the `internetarchive` script to start dumping selected creators or collections. Ask how to do it I'll help.

> Links to Archive.is.

Story straight: You're questioning the ethics and strength of the Internet Archive to host right-wing content, **using archived links on a service run by a IA employee** whom I know through dealing with IA and who inspired me to do what I do - that cites unsavory anonymous individuals on /pol/ spouting racial and ethnic epithets. All the while IA hosts probably about 80 percent of the [rantings of FBI informant Christopher Cantwell] (https://archive.org/search.php?query=creator%3A%22Christopher+Cantwell%22&sort=-date), every revision of the Anarchist Cookbook, not to mention they host even mild centrists content like Sargon - no I should totally take your word that IA isn't committed and will censor content based on it's political leanings.

IA sued for and won the right to talk about how they received a National Security Letter.

If I had serious doubts ever about IA hosting something political, I'd quit what I do. I've never had those doubts ever seriously.

Closed with prejudice. I'll punt any PRs that enable upload to those sites unless @antonizoon overrides me

**Comment by DuckHP** [comment]
> It might be a good idea to not pull all eggs in one basket.
> Another good idea: IPFS the videos with https://mafintosh.github.io/playback/

As far as i'm aware, BitChute offers channel-importing from e.g YouTube channels for author.

> @vxbinaca I would like to make a claim that Internet Archive (as an organization) will also delete content, not for guns, but other "right wing" contents.
> http://archive.fo/t9MPS http://archive.fo/Og47p

Instead of /pol/ , wouldn't seeking an actual statement from IA be more constructive?

**Comment by DonaldTsang** [comment]
@vxbinaca 
> So you want to put further barriers up to people getting access to the data?

Not really, since things like Siderus Orion (https://orion.siderus.io/) will make IPFS easier to use. Adoption to new technology takes time

> Story straight: You're questioning the ethics and strength of the Internet Archive to host right-wing content, using archived links on a service run by a IA employee...
All the while IA hosts probably about 80 percent of the rantings of FBI informant Christopher Cantwel...
If I had serious doubts ever about IA hosting something political, I'd quit what I do. I've never had those doubts ever seriously.

For this I will talk to @antonizoon to resolve, because this is more of an issue of "the weakest link".

@DuckHP 
> As far as i'm aware, BitChute offers channel-importing from e.g YouTube channels for author.

Good to hear that, but IPFS-by-default should be a good goal
> wouldn't seeking an actual statement from IA be a bit more constructive, than "dey bloxing muh dah rrayt wing content"
But i'm fairly certain there are quite a few transparency requirements to running a donation funded non-profit/NPO organization such as The Internet Archive.

Mind if I ask, is Wikipedia subjected to the same NPO requirements? If so, then it is a non-argument as NPO restrictions are not enough to make things "open by requirement" (see https://ggwiki.deepfreeze.it/index.php?title=Wikipedia for example). If not, than I may be mistaken.

**Comment by vxbinaca** [comment]
You're asking we add in functionality that will future break tubeup, which people rely on by the way. I'm not just talking about me I'm talking about IA staff and a bunch of randos.

You have options on hand right now that do the functionality you want. You can combine `youtube-dl` and `internetarchive` with your IPFS setup by scraping whatever topic you want from the site, or mirror the whole site like [this project wants to do](http://iabak.archiveteam.org/).

That's fine you don't trust IA. Again, scrape off what they host for yourself. It's easy.

D-Tube/BitChute is not happening it's not in our scope.

**Comment by vxbinaca** [comment]
Thank you @DuckHP however (not due to you) I'm locking this.
