### ISSUE TITLE
Possible to upload without going in 'Mirrortube' collection

### ISSUE THREAD

**Issue by brylie** [bibanon/tubeup#76]
When uploading videos, they are automatically added to the 'Mirrortube' collection. Is it possible to upload with tubeup without the videos getting added to Mirrortube collection?

**Comment by vxbinaca** [comment]
- Staff made a bot that transfers tubeup uploads based on tags to that collection, because they don't want people polluting Community Videos. When you use tubeup with no arguments that's what you're doing.
- You can make your own collection and put files into it. After [reading this guide](https://archive.org/about/faqs.php#Collections) email staff and ask them they make a collection for you. When you mirror a video you'd use a metadata modifying flag like `--metadata=collection:ytpmv-mad` that would put the video in that collection.

Closing because this isn't a problem with tubeup and we're not the internet archive who you should be contacting.
